### ISSUE TITLE
Search to troubleshoot files without extensions

### ISSUE THREAD

**Issue by wzygxlz** [dnGrep/dnGrep#1218] opened 2024-10-28 15:26 UTC
As shown in the figure, I want to exclude files without extension from the search, but typing "*." in the exclusion box has no effect. It didn't work.

![1](https://github.com/user-attachments/assets/340cfbf2-b8cd-4df2-814e-2c737678a37a)

However, when I specify "*." in the search criteria, I get the file without extension, as shown in the figure.

![2](https://github.com/user-attachments/assets/c1c96a7b-ab0e-4e00-a5cb-e1de1e53c8f9)

**Comment by fade2gray** [comment] 2024-10-28 16:55
I was thinking of using this regular expression in 'Patterns to match', `.*\.\w{1,4}$` - it works in [regex101](https://regex101.com/r/mnUDN4/1), but not as a match filter.

**Comment by doug24** [comment] 2024-10-28 21:27
oh, so much happening here.

First the easy one, the expression fade2gray suggested should work, but there is a bug mangling the expression. I'll have to think about this to find the best way to fix it.  

Maybe not very robust, but the regular expression `\.` will work to find only files with a dot character.  Make sure the file filter type is set to Regular Expression.

Back to the original question - when using the Wildcard file filter type, the patterns to match and patterns to exclude are applied very differently.  The pattern to match is applied first and uses custom code to match a Windows file pattern - the comment in the code says "Not an exact duplicate of the internal Windows implementation, but most common patterns are supported" based on these two references:
https://blogs.msdn.microsoft.com/jeremykuhne/2017/06/04/wildcards-in-windows/
https://devblogs.microsoft.com/oldnewthing/20071217-00/?p=24143
The first reference includes the pattern `*.` to match all file names without extensions, and that is what dnGrep does for the include pattern.

The patterns to exclude are converted to regular expressions for matching, and this was done to match folders as well as files when excluding. It's not the most sophisticated conversion.  Yes, it should support converting `*.` to a regular expression to match files without extensions, but that was overlooked.

**Comment by doug24** [comment] 2024-11-12 23:53
Fixed in [4.2.113](https://github.com/dnGrep/dnGrep/releases/tag/v4.2.113.0)

**Closed** 2024-12-04 15:26 UTC
Labels: bug
