### ISSUE TITLE
Search pops up numerous SaveAs file dialogs for .doc files

### ISSUE THREAD

**Issue by InfoBube** [dnGrep/dnGrep#629] opened 2022-01-27 16:19 UTC
When searching for .doc files, dngrep will pop up Save As file dialogs for certain .doc files. When repeating the process, the dialog pops up again for the exact same select files (only a fraction of the .doc files in the searched folders) so the phenomenon seems to have something to do with the properties or contents of those files.

Any help in finding the cause would be helpful. As is, I can't use dngrep with .doc for fear of crashing Windows with the large number of dialogs popping up from extensive searches.

This is on Windows 10, German regional settings with v3 of dngrep but already occurred on v2.93.

Thanks!

**Comment by doug24** [comment] 2022-01-27 21:11
If you are seeing Save As file dialogs, they are from Word itself.  The only save file dialog in dnGrep is for the search results report outputs.  

The plug-in to search the old-style Word documents opens the .doc file using the Word application. dnGrep sets visibility flag for Word to false so you don't see the application open. It opens the .doc files as read-only and disables all macros. It calls some Word automation commands to extract all the text, closes the file, and closes Word.  It's not clear why Word would think the file needs to be saved when it is opened in read-only mode, but it sounds like there is something in these document that Word automatically updates when the document is opened.

Checking the Word documentation again, there is an optional `SaveChanges` argument to the document `Close` method.  I can try setting that to the value `wdDoNotSaveChanges`, and see if that helps.

Using Word to do this is very inefficient and prone to errors.  It would be great to be able to get the text from a old Word document without using Word itself, but I have been unable to find any free open source library that can read the old file format.

**Comment by InfoBube** [comment] 2022-01-27 21:30
Thank you very much for your quick and clear reply!

I'd be very happy to try your suggested fix. As for non-native ways to get at the text inside .doc files, I found this list of converters (some of them free / open source) but maybe you've come across those already and haven't found them usable:

- XDoc2txt for many file types
- Kryloff GetText (HTM HTML RTF PDF WPD HLP DOC XLS PPT XML)
- GetTextIFilter (RTF DOC DOT PPT XLS XLT CS CPP H TXT HTM HTML)
- SilverCoders DocToText (DOC)
- AntiWord (DOC)

**Comment by doug24** [comment] 2022-01-28 01:57
I updated the Word doc plugin and merged it into master.  If you are able to build the project, you can try it now.  Otherwise, I'll have another release in a few weeks.

**Comment by InfoBube** [comment] 2022-01-28 21:40
Thanks for doing this! I'll wait for the next release.

**Comment by celeron533** [comment] 2022-02-17 12:35
One of my friends who is using other file content search tool (not dnGrep) has the same issue these days. I guess it is a change on MSOffice side when pulling winword.exe in background.
`taskkill /F /IM winword.exe` will kill Word processes. But be careful to save your own work first before execute this command.

**Comment by InfoBube** [comment] 2022-02-17 21:31
Thanks for chiming in and recommending taskkill to get back in control. Will wait to see if next release solves the issue. If not, will resort to your fix. Cheers.

**Comment by doug24** [comment] 2022-02-26 20:52
Fixed (hopefully) in v3.0.29.0

**Comment by InfoBube** [comment] 2022-02-27 12:37
Can confirm no unwanted Word dialogs popping up anymore with this latest update. Thank you *very* much!

**Comment by InfoBube** [comment] 2022-02-27 12:43
Noticed a slight issue: some of the searched .doc files now show up in Windows' recent files list, making it sort of unusable after a search. I suspect it may be just those ones that used to pop up the SaveAs dialog but am not entirely sure. It certainly looks like it isn't all the .doc files that were searched.

**Comment by doug24** [comment] 2022-03-27 16:58
I'm not able to do anything about the recent files list, I have looked for a solution.  The problem is with the old style .doc files, Work is actually opening the files and does not distinguish between a hidden automation session and a user opening the file to view or edit the document.

**Comment by InfoBube** [comment] 2022-03-27 18:41
I see. Thanks for looking into it! I should probably just take the time to convert all my .doc's to .docx's but it's a daunting task...

**Closed** 2022-03-28 01:06 UTC
