### ISSUE TITLE
Invalid text highlight

### ISSUE THREAD

**Issue by kvknyazev** [dnGrep/dnGrep#347] opened 2019-07-15 09:51 UTC
Hi!
I'm trying dnGrep to search text throughout archived (7z) logs. It works but highlights is not aligned correctly (see attached image). Problem is occurred on archived UTF8 texts. 
Thanks for your app!
Best regards, Konstantin Knyazev

![dnGrep](https://user-images.githubusercontent.com/34535317/61207937-f8590b80-a6fe-11e9-94b5-ca0f615110bb.png)

**Comment by doug24** [comment] 2019-07-15 23:52
I was not able to reproduce this problem.  I tried with UTF-8 encoded files (no byte order mark) with both Unix and Windows line endings.  Files were archived with 7zip in the 7z format.  It is also strange that the highlights are nowhere close to the 'Kafka' search string - my guess is that it is an encoding problem.

Questions:
1) What version of dnGrep are you using?
2) Do you have a file encoding selected, or are you using the default Auto detection?
3) Can you attach a sample archive that reproduces the problem?

**Comment by kvknyazev** [comment] 2019-07-16 11:02
1. I use 2.9.153 version
2. I used default Auto detection
3. See attachment
Yes, problem is in Auto encoding detection, when UTF8 is specified text highlighted correctly. Probably it is because russian chars used in text.
[test.zip](https://github.com/dnGrep/dnGrep/files/3396743/test.zip)

**Comment by doug24** [comment] 2019-07-17 00:40
Thank-you for the test file.  it's similar to a problem with PDF files that I fixed recently - the file encoding wasn't being checked when the file was extracted from the archive.  I have a change queued up, and will build a release soon.

**Comment by kvknyazev** [comment] 2019-07-17 05:48
Thank you very much!

**Comment by doug24** [comment] 2019-08-02 01:32
Fixed in release 2.9.160

**Closed by doug24** 2019-08-02 01:32 UTC
