### ISSUE TITLE
really slow typing in 'search in box'

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#213] opened 2014-12-01 00:55 UTC
_From [ahz...@gmail.com](https://code.google.com/u/112749914714431718909/) on May 13, 2014 13:51:29_

What steps will reproduce the problem? 1. Type in the 'search in box' What is the expected output? What do you see instead? It's so slow it reminds me of my 300bps modem from the 1980's.  There can be a delay of several seconds where nothing changes in the main window, while there are slow updates to the title bar. What version of the product are you using? On what operating system? I am using 64-bit dngrep on 2.7.2, and I had a problem with an older version.

I use a fast Dell laptop with an Intel i7 CPU.

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=210_

**Comment by klonos** [comment] 2017-06-18 01:07
I think that it is safe to close this issue after 3 years.

**Comment by doug24** [comment] 2017-06-18 23:36
I'm guess this was once caused by the code validating the regular expression, but it doesn't appear to a problem any more

**Closed by doug24** 2017-06-18 23:36 UTC
Labels: bug, imported, Priority-Medium
