### ISSUE TITLE
double click on result line should open file with default application

### ISSUE THREAD

**Issue by pstein** [dnGrep/dnGrep#889] opened 2023-07-03 20:23 UTC
I search a pattern inside all *.pdf files in  a partition

The result list contains some matches.

if I click now on a result line the pdf files is opened - as text file in text editor.

How can I tell dngrep to always open a file with the local system default application (here: PDF Viewer)?

**Comment by doug24** [comment] 2023-07-03 20:32
This is a duplicate of #882.  It's been fixed, planning the next release for next week, July 12th.

**Comment by doug24** [comment] 2023-07-12 00:15
Fixed in [v4.0.45](https://github.com/dnGrep/dnGrep/releases/tag/v4.0.45.0)

**Closed** 2023-07-17 12:53 UTC
Labels: duplicate
