### ISSUE TITLE
Something broke down in dnGrep. Check the error log for details

### ISSUE THREAD

**Issue by smoore-33** [dnGrep/dnGrep#892] opened 2023-07-03 23:37 UTC
The above error happened right after I installed dnGREP.4.0.26.x64.msi over dnGREP.3.2.330.x64.msi. I'll attach a printscreen of the search and/or log data, if someone tells me how.  It looks like there are a lot of errors.

Is it safe to just reinstall the older version on top of the newer one, or do I need to uninstall and loose settings? Thanks.

**Comment by smoore-33** [comment] 2023-07-03 23:41
Reinstalling over an newer version didn't work, so I'm reinstalling from scratch.

**Comment by doug24** [comment] 2023-07-03 23:43
Sounds like a duplicate of #887.  If that looks like what you are seeing, delete dnGREP.Settings.dat in the %appdata%\dnGREP folder and restart.

**Comment by doug24** [comment] 2023-07-04 00:00
If that isn't it, then attach the Grep_Error_Log.xml file here.  You can find it in C:\Users\_username_\AppData\Roaming\dnGREP\logs

**Comment by smoore-33** [comment] 2023-07-04 00:24
That may well be it. I’m pressed for time, so won’t be able to reinstall 4 and test it now. I’ve reinstalled 3. Will there be an update to resolve the issue (if it is a duplicate of #887 <https://github.com/dnGrep/dnGrep/issues/887> )? Thanks so much.

**Comment by doug24** [comment] 2023-07-04 00:32
You do not have to reinstall it again (unless you've already uninstalled it).  Just delete the dnGREP.Settings.dat in the %appdata%\dnGREP folder and restart.

If this is the same issue as #887, there will not be any fix to the application, the only way to fix it is to delete the dnGREP.Settings.dat file, or manually edit it to remove the binary encoded settings.  The past few releases have had code to convert the old binary encoded data to plain text.  I don't know why yours did not get converted, it has worked for all but a few users.  The binary encoder no longer exists in the .NET 7 libraries, so the application cannot read the binary data and the conversion is no longer possible.

**Comment by smoore-33** [comment] 2023-07-04 21:19
Thanks so much for your follow-up. I have uninstalled 4 and reinstalled 3. I don’t have time to do it now, but I’ll refer back to this message when I do and follow your advice.

 

I did not install all past updates, so I probably missed the one(s) that did the conversion of dnGREP.Settings.dat. If you could let me know what release(s) did the conversion, I could download it, install it, which should set me up to go to the latest release of 4. Correct?

 

If that doesn’t work, I will delete the dnGREP.Settings.dat file and try that.

 

Thanks again.

**Comment by doug24** [comment] 2023-07-04 21:50
The settings conversion was first released in [3.0.154](https://github.com/dnGrep/dnGrep/releases/tag/v3.0.154.0) on September 5, 2022, and in each subsequent five 3.1.x and 3.2.x versions.

https://github.com/dnGrep/dnGrep/releases

**Comment by doug24** [comment] 2023-07-08 16:42
I still don't know what error you are seeing, but I went back and reviewed #887 and found this is something I can fix. Will include in the next release.

**Comment by smoore-33** [comment] 2023-07-09 00:22
The error message that showed up was "Something broke down in dnGrep. Check the error log for details". I didn't try to figure it out further from the logs, since I haven't used them before. I'm now at Version 3.2.330.0, so if you're able to create a release that resolves #887, I'll look forward to trying the new release. Thanks for all your efforts.

**Comment by doug24** [comment] 2023-07-12 00:15
Fixed in [v4.0.45](https://github.com/dnGrep/dnGrep/releases/tag/v4.0.45.0)

**Comment by smoore-33** [comment] 2023-07-14 20:37
Great, thanks!

**Closed** 2023-07-17 12:53 UTC
