### ISSUE TITLE
PDF results-preview: wrong character

### ISSUE THREAD

**Issue by pantak1** [dnGrep/dnGrep#428] opened 2020-06-18 18:10 UTC
Hi,
I use version 2.9.248.0 of dngrep.
When I search something in attached pdf-file, wrong characters are shown in search results.
Instead of § (ANSI-char-code=167, 0xA7) a question mark is shown.
Every PDF-viewer is showing the right character.
The resulting text-file attached is the output of pdftotext-extraction.
It contains the right character.
Only the results-preview shows a question mark.
regards
Pantak
[2_Para.pdf](https://github.com/dnGrep/dnGrep/files/4800372/2_Para.pdf)
[2_Para.txt](https://github.com/dnGrep/dnGrep/files/4800373/2_Para.txt)
![original_PDF-content](https://user-images.githubusercontent.com/46825664/85056419-7ccdcd00-b19f-11ea-87f8-b22e3f465ceb.png
![dngrep-results-preview](https://user-images.githubusercontent.com/46825664/85056463-90793380-b19f-11ea-806e-8c75cad577af.png)
)

**Comment by doug24** [comment] 2020-06-19 00:09
Yes, I see the same result.  

Info on this problem:  dnGrep uses a third-party tool to extract text from the PDF file, tries to get the encoding of the extracted text, and then searches the extracted text.  I verified that the extracted text is correct, and Notepad++ detects the encoding of the plain text version as "ANSI", and displays the characters correctly.

In dnGrep, if you set the Encoding option to "Auto Detection", dnGrep uses a library to detect file encoding, and that code detects the encoding as Simplified Chinese.   That's why they don't display correctly.   A few months ago I changed the encoding library.  Today I retrieved the old code and tried it - with the exact same results.

If you set the encoding manually to "Western European (Windows)" in the encoding selector, you will get the correct display output.

I'm wondering if the detection error is caused by small number of characters in the file?  Have you tried this with a larger PDF?  Does it work on larger files?

**Comment by pantak1** [comment] 2020-06-19 11:21
Thank you for the detailed explanation,
Yes, also the complete PDF (2 pages) shows the problem. Attached pictures.
You see the dngrep result apart from the question marks in row 77, in rows 83 and 86 some chinese characters, where there should be some other characters (ü, ä, ö, ...), as the original picture shows.
Remark: The encoding of the original PDF is "identiny-H" as shown in the third picture.
But this should not be a problem, because every PDF-reader shows  the right characters.

![dngrep-result-complete-pdf](https://user-images.githubusercontent.com/46825664/85127320-7dae3f80-b22f-11ea-8741-344827bdd5af.png)
![part-of-complete-original-pdf](https://user-images.githubusercontent.com/46825664/85127390-9f0f2b80-b22f-11ea-8faa-76c7cfc193b0.png)
![dngrep-original-pdf-fonts-encoding](https://user-images.githubusercontent.com/46825664/85127408-a6363980-b22f-11ea-8e57-491c86b04fe2.png)

**Comment by doug24** [comment] 2020-06-20 21:58
The "identiny-H" encoding is only valid within the PDF, once the file is converted to plain text for search, the encoding of the plain text file is something different.

There is a command line argument for pdftotext.exe to output the plain text in UTF-8.  Using this encoding the characters are decoded correctly.

Fixed in 2.9.256

**Comment by pantak1** [comment] 2020-06-21 14:44
Unfortunately the new version 256 has another drawback:
It uses a new version 4.02 of pdftotext which does not work with attached Test.pdf.
[Test.pdf](https://github.com/dnGrep/dnGrep/files/4809636/Test.pdf)
You can see the text output attached.
[Test-output-with-pdftotext_4.02.txt](https://github.com/dnGrep/dnGrep/files/4809643/Test-output-with-pdftotext_4.02.txt)
Instead the version 3.02 of pdftotext is working fine.
[Test-output-with-pdftotext_3.02.txt](https://github.com/dnGrep/dnGrep/files/4809644/Test-output-with-pdftotext_3.02.txt)

Thus the dngrep 256 does not recognize the first word "Information" but dngrep 248 with pdftotext 3.02 does.
![dngrep-256-with-pdftotext_4](https://user-images.githubusercontent.com/46825664/85227513-4c27a680-b3de-11ea-9e01-69eb71144a1c.png)
![dngrep-248-with-pdftotext_3](https://user-images.githubusercontent.com/46825664/85227516-53e74b00-b3de-11ea-8f2b-ca4e9031ef93.png)

Trying to use pdftotext 3.02 with dngrep 256 does not work.

My suggestion: 
Leave old pdftotext 3.02 and if needed the encoding must be set manually to the required one, as you described above in your first comment.
And do not use the command line argument for pdftotext.exe to output the plain text in UTF-8.

**Comment by doug24** [comment] 2020-08-17 23:58
In release 2.9.263, I added option to customize the pdftotext command line.  You can disable UTF-8 encoding, and you can replace pdftotext.exe version 4 with 3.02 by overwriting the installation file.

**Closed** 2020-09-12 21:21 UTC
