### ISSUE TITLE
String not found in Excel with cells in Scientific format

### ISSUE THREAD

**Issue by frankN10** [dnGrep/dnGrep#951] opened 2023-09-18 19:21 UTC
Hi, I'm facing an issue where dnGrep does not find the search string in Excel files, when there are other cells using "Scientific" format and there is a zero in one of those cells. Changing the zero value to something >0, or changing the format to "General" will let dnGrep find it. Attached is a simple example where the search string 22477016 is not found.
[](url)
[test - Copy.xlsx](https://github.com/dnGrep/dnGrep/files/12652446/test.-.Copy.xlsx)

**Comment by doug24** [comment] 2023-09-19 00:07
As you have figured out, the problem is in the cell `0.00E+00`.  The cell value is 0, and the formatting displays it as you see it.  There is code to convert the value 0 to a string for searching - this code attempts to reproduce how Excel displays numeric values with a format.  But the code does not handle this value and format combination correctly and throws an exception which stops processing the file before it gets to any other cells.

This code is in a library, ExcelNumberFormat, which hasn't been updated in three years and no indication when it may be updated again, if ever. Welcome to the wonderful world of open-source software. I've already taken on private maintenance and builds of two other libraries used by dnGrep, and I'm really reluctant to take on more.  So, I don't know what to do with it.

I could catch the exception and skip that cell, which would solve your problem, but not if you were trying to search for `0.00E+00`

**Comment by frankN10** [comment] 2023-09-19 12:28
I understand that you are relying on other SW for dnGrep and your hands are bound a bit. Skipping the cell (there may be multiple of those in a file) is certainly better and continuing the search than completely skipping the file.
It would be also good to provide an error/warning message to the user that such a cell has been found/skipped. At least it would give a hint to the user that a 0.00E+00 entry was skipped in case they search for that string.

**Comment by doug24** [comment] 2023-09-20 22:56
I have found a good solution for this and will include it in the next release.

**Comment by doug24** [comment] 2023-10-10 23:34
Fixed in [v4.0.129.0](https://github.com/dnGrep/dnGrep/releases/tag/v4.0.129.0)

**Closed** 2023-10-17 00:31 UTC
