### ISSUE TITLE
Can you provide a portable dnGrep version?

### ISSUE THREAD

**Issue by pstein** [dnGrep/dnGrep#679] opened 2022-06-03 15:43 UTC
I miss a portable version of dnGrep.

Can assemble a corresponding *.zip package and offer a download link.

Thank you

**Comment by doug24** [comment] 2022-06-03 16:13
Duplicate of #238.  I haven't tried it, but it looks like some people are using [Universal Extractor](https://github.com/Bioruebe/UniExtract2).

When I have some time, I'll see if I can find a way of automating creating a zip file.  dnGrep is built from source securely on AppVeyor, and the resulting msi files are uploaded for scanning and signing by SignPath.  A zip archive would have to follow a similar path.

**Comment by pstein** [comment] 2022-06-06 16:27
When I use Universal Extractor I can do it, BUT when I double click 8on 64bit Win10 v21H2 I got the following error:

```
<logevent time="2022-06-06 18:25:15.0344" level="Error" logger="dnGREP.WPF.App">
  <message>Failure in application startup</message>
  <exception>System.BadImageFormatException: Could not load file or assembly &apos;dnGREP.Everything, Version=3.0.64.0, Culture=neutral, PublicKeyToken=f16c685bbd14faeb&apos; or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: &apos;dnGREP.Everything, Version=3.0.64.0, Culture=neutral, PublicKeyToken=f16c685bbd14faeb&apos;
   at dnGREP.WPF.BaseMainViewModel..ctor()
   at dnGREP.WPF.MainViewModel..ctor()
   at dnGREP.WPF.MainForm..ctor(Boolean isVisible)
   at dnGREP.WPF.App.Application_Startup(Object sender, StartupEventArgs e)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
</exception>
</logevent>

So this seems not to work

```

**Comment by pstein** [comment] 2022-06-06 17:57
You are right. Everything64.dll was missing.
No clue why I did not copy it
Thx

**Closed** 2022-07-03 00:22 UTC
