### ISSUE TITLE
Encoding autodetection issue

### ISSUE THREAD

**Issue by StoyanDimitrov** [dnGrep/dnGrep#364] opened 2019-09-27 15:26 UTC
I'm searching for the following string "на луната" in [this file](https://github.com/dnGrep/dnGrep/files/3663397/dnGrep.txt). The file has windows-1252 characters. If I switch to the right encoding then the search returns result but as it seems the auto-detection is not able to pick the right encoding.
I tried to minimize the example file as much as possible and attached is the result.
I guess is not related to #180 because the source file is not UTF-8.

**Comment by doug24** [comment] 2019-09-28 01:05
I can reproduce this problem, but I don't know why.  dnGrep uses the Mozilla UDE code (in c#) to detect character sets, but it is failing on this file.  Notepad++, which also uses UDE (in c++) does correctly detect the sample file as windows-1252.   Will have to investigate more.

**Comment by doug24** [comment] 2019-10-13 21:55
Fixed in release 2.9.174.  Found and fixed the bug in the UDE used code in the dnGrep build.  

While researching this, I came across the [UTF-Unknown](https://github.com/CharsetDetector/UTF-unknown) project.  It looks better maintained and we may want to change dnGrep to use this project in the future.  I did not at this time because it will require regression testing.

**Closed** 2019-10-20 18:32 UTC
