### ISSUE TITLE
Bug in replace function with regex

### ISSUE THREAD

**Issue by BeysensJona** [dnGrep/dnGrep#437] opened 2020-08-17 12:49 UTC
When I use the regex search function, the replace function does not work when using look back/ahead functions. For example, when I run (?<=\$.*)(\bM\b)(?=.*\$) on the test pattern "this is a test $M+1$", the character M is found but I cannot replace it with another character (also not using the "test expression" function).

**Comment by doug24** [comment] 2020-08-17 23:46
Yes, you are correct, the replace function does not work when you use lookback/lookahead.  

The problem is with the dnGrep feature that allows users to choose replace/no replace of each match found.  A 'match' is a location and length in a block of text and only contains the match and not the surrounding context.  Without the context, the lookback/lookahead will fail during the replace operation.   I don't know of any way to fix this, but I'll think about it.

I'm not sure I understand your regex above:  I'm guessing you are looking for a single M character between two dollar signs.  But as-is, the '$' in you regex will match end of line.  I think you need to use [$] to match the literal dollar sign.  Here's the regex I used:
`(?<=[$].*)(\bM\b)(?=.*[$])`

As a work-around, you may be able to use capture groups instead, such as this:
`(.*[$])(\bM\b)(.*[$])`
Which give you three numbered capture groups.  Then if you want replace 'M' with 'X', you would use this for the replace expression:
`$1X$3`

'$1' refers to group 1 contains everything before the M, and '$3' refers group 3 contains everything after the M.  (yet another meaning for the $ character).

**Comment by doug24** [comment] 2020-09-12 21:19
Fixed in v2.9.270

**Closed** 2020-09-21 14:06 UTC
Labels: bug
