### ISSUE TITLE
Version v4.0.69.0 Crashes on Opening on Windows 2016 Server

### ISSUE THREAD

**Issue by wburchard** [dnGrep/dnGrep#933] opened 2023-08-25 12:17 UTC
When I attempt to open dnGrep after installing it on a Windows 2016 server, I get a popup with the following text:

Something broke down in dnGrep.  Check the error log for details:  <path to error log>

Error Log Content
`<logevent time="2023-08-25 07:13:59.9716" level="Error" logger="dnGREP.Common.GrepSettings">
  <message>Error converting settings key [PreviewWindowWrap] of type [System.Boolean] from value [AAEAAAD/////AQAAAAAAAAAEAQAAAA5TeXN0ZW0uQm9vbGVhbgEAAAAHbV92YWx1ZQABAAs=]</message>
  <exception>System.FormatException: String &apos;AAEAAAD/////AQAAAAAAAAAEAQAAAA5TeXN0ZW0uQm9vbGVhbgEAAAAHbV92YWx1ZQABAAs=&apos; was not recognized as a valid Boolean.
   at System.Boolean.Parse(ReadOnlySpan`1 value)
   at System.String.System.IConvertible.ToBoolean(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at dnGREP.Common.GrepSettings.Get[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 854</exception>
</logevent>
<logevent time="2023-08-25 07:14:00.2350" level="Error" logger="dnGREP.Common.GrepSettings">
  <message>Error converting settings key [StartDate] of type [System.Nullable`1[System.DateTime]] from value [AAEAAAD/////AQAAAAAAAAAEAQAAAA9TeXN0ZW0uRGF0ZVRpbWUCAAAABXRpY2tzCGRhdGVEYXRhAAAJEAAAAAAAAAAAAAAAAAAAAAAL]</message>
  <exception>System.InvalidOperationException: Null default is not allowed for key StartDate
   at dnGREP.Common.GrepSettings.GetDefaultValue[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 984
   at dnGREP.Common.GrepSettings.Get[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 813</exception>
</logevent>
<logevent time="2023-08-25 07:14:00.2350" level="Error" logger="dnGREP.WPF.App">
  <message>Failure in application startup</message>
  <exception>System.InvalidOperationException: Null default is not allowed for key StartDate
   at dnGREP.Common.GrepSettings.GetDefaultValue[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 984
   at dnGREP.Common.GrepSettings.Get[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 862
   at dnGREP.Common.GrepSettings.GetNullable[T](String key) in C:\projects\dngrep\dnGREP.Common\GrepApplicationSettings.cs:line 726
   at dnGREP.WPF.BaseMainViewModel.LoadSettings() in C:\projects\dngrep\dnGrep.WPF\ViewModels\BaseMainViewModel.cs:line 866
   at dnGREP.WPF.MainViewModel.LoadSettings() in C:\projects\dngrep\dnGrep.WPF\ViewModels\MainViewModel.cs:line 714
   at dnGREP.WPF.BaseMainViewModel..ctor() in C:\projects\dngrep\dnGrep.WPF\ViewModels\BaseMainViewModel.cs:line 36
   at dnGREP.WPF.MainViewModel..ctor() in C:\projects\dngrep\dnGrep.WPF\ViewModels\MainViewModel.cs:line 46
   at dnGREP.WPF.MainForm..ctor(Boolean isVisible) in C:\projects\dngrep\dnGrep.WPF\Views\MainView.xaml.cs:line 97
   at dnGREP.WPF.App.Application_Startup(Object sender, StartupEventArgs e) in C:\projects\dngrep\dnGrep.WPF\App.xaml.cs:line 63</exception>
</logevent>`

**Comment by wburchard** [comment] 2023-08-25 12:19
.NET v7.0.10 is installed on the server.

**Comment by doug24** [comment] 2023-08-25 14:18
dnGrep packages the .NET runtime with the application, so you don't need to install it separately.

This is a duplicate of #926.  The problem is that the binary serialization is no longer supported, and I missed some of the conversions.  I have a fix for the next release, but in the meantime, you can fix this by modifying your dnGREP.Settings.dat file in %appdata%\dnGREP (C:\Users\\_username_\AppData\Roaming\dnGREP).

If you don't really care about preserving your old settings, you can rename your existing dnGREP.Settings.dat (maybe go back to modify it), and a new one will be created.

Otherwise, open it in an editor and modify or remove any settings that have values like this:

<item key="StartDate">AAEAAAD/////AQAAAAAAAAAEAQAAAA9TeXN0ZW0uRGF0ZVRpbWUCAAAABXRpY2tzCGRhdGVEYXRhAAAJEAAAAAAAAAAAAAAAAAAAAAAL</item>
to
<item key="StartDate"></item>
(same for EndDate)

<item key="PreviewWindowWrap">AAEAAAD/////AQAAAAAAAAAEAQAAAA5TeXN0ZW0uQm9vbGVhbgEAAAAHbV92YWx1ZQABAQs=</item>
to
<item key="PreviewWindowWrap">False</item>

There may be others - all the values should be readable - remove the ones that look like these above. Save the file and start dnGrep.

**Comment by wburchard** [comment] 2023-08-25 18:23
Thank you!Sent via the Samsung Galaxy S23 Ultra 5G, an AT&T 5G smartphone
-------- Original message --------From: Doug P ***@***.***> Date: 8/25/23  10:19  (GMT-05:00) To: dnGrep/dnGrep ***@***.***> Cc: wburchard ***@***.***>, Author ***@***.***> Subject: Re: [dnGrep/dnGrep] Version v4.0.69.0 Crashes on Opening on Windows 2016 Server (Issue #933) 
dnGrep packages the .NET runtime with the application, so you don't need to install it separately.
This is a duplicate of #926.  The problem is that the binary serialization is no longer supported, and I missed some of the conversions.  I have a fix for the next release, but in the meantime, you can fix this by modifying your dnGREP.Settings.dat file in %appdata%\dnGREP (C:\Users\username\AppData\Roaming\dnGREP).
If you don't really care about preserving your old settings, you can rename your existing dnGREP.Settings.dat (maybe go back to modify it), and a new one will be created.
Otherwise, open it in an editor and modify or remove any settings that have values like this:
AAEAAAD/////AQAAAAAAAAAEAQAAAA9TeXN0ZW0uRGF0ZVRpbWUCAAAABXRpY2tzCGRhdGVEYXRhAAAJEAAAAAAAAAAAAAAAAAAAAAAL
to

(same for EndDate)
AAEAAAD/////AQAAAAAAAAAEAQAAAA5TeXN0ZW0uQm9vbGVhbgEAAAAHbV92YWx1ZQABAQs=
to
False
There may be others - all the values should be readable - remove the ones that look like these above. Save the file and start dnGrep.

**Comment by doug24** [comment] 2023-09-15 02:26
Fixed in v4.0.115

**Closed by doug24** 2023-09-15 02:26 UTC
