### ISSUE TITLE
slow search after many files found also can not cancel

### ISSUE THREAD

**Issue by PaltryProgrammer** [dnGrep/dnGrep#828] opened 2023-02-17 05:39 UTC
Thank You for providing dnGrep please see attached PNGs demonstrate slow search after many thousands of files found . also can not cancel same Thank You Kindly
![slow search of boost after many thousands](https://user-images.githubusercontent.com/48535920/219558693-3190579c-296d-4ec8-be76-d55a97b3209c.gif)
![can not cancel search of boost after many thousands of files found](https://user-images.githubusercontent.com/48535920/219558722-263b95f9-f3ef-44de-95de-530f5330bce7.gif)

**Comment by PaltryProgrammer** [comment] 2023-02-17 18:54
attached please see same search w/ "Search parallel" unchecked Thank You Kindly
![Search Does Not Progress ](https://user-images.githubusercontent.com/48535920/219759608-d605c798-292b-4dd9-ae45-c7005520b74a.gif)

**Comment by doug24** [comment] 2023-02-17 19:57
I downloaded the Boost source code and binaries and can reproduce this now.  The problem is with the *.lib files - first, the *.lib files are not detected as binary files because they start with `!<arch>` and more text characters - not sure yet how to fix this.  Next, is the "Whole word" setting: there are no 'lines' in a binary file, so the line lengths are very long - millions of characters, and the code has to check each character for a start of word boundary and +2 characters for end of word boundary.  There is no check for cancel in that loop, so I can fix that.

I'm guessing you really don't want to be searching in the lib files, so for now, just put `*.lib` in `Patterns to exclude`.  Or, even better, just include the file types you want - something like *.hpp;*.cpp.

**Comment by doug24** [comment] 2023-02-21 19:38
Fixed in v3.2.279

**Closed** 2023-02-25 19:03 UTC
