### ISSUE TITLE
replacing text is not working, it's so strange

### ISSUE THREAD

**Issue by mehfou** [dnGrep/dnGrep#440] opened 2020-08-18 15:54 UTC
![44](https://user-images.githubusercontent.com/69862187/90536055-8632e000-e1b6-11ea-8371-36db607095ce.PNG)

am I doing something wrong? replace is not working.

if I search for plain chracters , this does not happen.

**Comment by doug24** [comment] 2020-08-18 17:08
What characters are those?  It's not clear to me why you would even get a search match with them there.

Can you copy the characters in to the message or tell me what the Unicode numbers are?

**Comment by mehfou** [comment] 2020-08-18 22:47
if you mean you can't see the screenshot, I am trying to search for "\b[.]" without quotation marks and replace it with ".." without quotation marks. 

sample text  : hello.this is a test
search result  : hello.this is a test(yellow highlighted on the dot)
replace result : hello.this is a test

and my expected result is : hello..this is a test

\b is very common regex that matches position between word character and non word character.

**Comment by doug24** [comment] 2020-08-18 23:05
In your screenshot above your backslash looks like a capital W with a strike-though.  That's why I did not understand. 

This is the same issue as #437:  The problem is with the dnGrep feature that allows users to choose 'replace/no replace' of each match found. A 'match' is a location and length in a block of text and only contains the match and not the surrounding context. Without the context, the word boundary constraint will fail during the replace operation. I don't know of how to fix this.  To work correctly, the regex replace operation should operate on the same block of text as the original search.  But there may be multiple matches within that block of text and it would replace them all, possibly not respecting the user's choice.

The code has been this way for 18 months, and two people found the same issue in two days?

**Comment by mehfou** [comment] 2020-08-19 01:05
oh my! that W with - in it looking sign stands for backslash in my country hahaha. that stands for the sign of Won(Korean currency) that is used to specify backslash in code patterns.

and I've read #437 post talking about similar problem, I also was about to use lookahead and lookbehind subexpressions in my search task, and thought your grouping workaround probably is worth a shot. Good insight for a solution.

here's what I was trying to achieve, can you help me write the right regex?

original regex : (?<=[a-z])[.](?=[a-z])
changed it to(in the search for field) :  (.*[a-z])([.])(.*[a-z])

replace with : $1..$3

sample text : hey.this is the test.and test is fun.to be continued.

replace result : hey.this is the test.and test is fun..to be continued.

* expected replace result : hey..this is the test..and test is fun.. to be continued.

so confusing, maybe I mislead again?

**Comment by doug24** [comment] 2020-08-19 02:45
I assumed that character must have some special meaning, otherwise the regex match would not work.  Now I know  :)

This expression will work in your test case:
regex:  `(\w)([.])(\w)`
replace:  `$1..$3`

\w will match any word character, unless you want to limit it to just lowercase ASCII.
You probably don't need any length qualifier, all you need is one character before and one after.  
By adding the .* it will be match greedy, making a single long match.
This is a good reference:  https://www.rexegg.com/regex-quickstart.html
In the dnGrep Test Window, click the "Highlight Groups" to visualize the match groups.

![image](https://user-images.githubusercontent.com/17227248/90586152-56baae00-e18b-11ea-91d1-b07cbb67f7d3.png)

**Comment by mehfou** [comment] 2020-08-19 05:51
Thanks for the new suggestion. If I am not misunderstood, I thought this program supports multiple searches and replacements in one go, is that legit? But I can't find where the "add more search" button or something like that is. All I see is to perform the search and replace in multiple files, but not multiple search and replace in one or multiple files.
Bookmark is useful to remember and reload them one by one to get the job done, but it is still not as convenient as doing it all at once. Maybe clicking the multiline checkbox is the key? Guess not.

and sometimes there're more than one search term in one expression, for example:

(\w)([.,?!])(\w)

say I should replace those puncutation marks respectively with .. ,, ?? and !!
How do I have to modify $1..$3 regex in such case?

cheers! keep up the great work =)

**Comment by doug24** [comment] 2020-08-19 14:26
The punctuation mark is the second capture group, so using the replace string:
`$1$2$2$3`
will double whatever character is matched.

No, you can't do multiple different search and replace in one operation.

**Comment by mehfou** [comment] 2020-08-20 13:41
Thank you doug ;) so each one parenthesized forms group with number 1,2,3... from left ryt?
would you please help me one last time about use of group capturing? I am so lost in the middle of nowhere 🤔

take a look for regex like this:

([a-zA-Z])([,.?!])([a-zA-Z])|([a-zA-Z])([,.?!])(\d)|(\d)([,.?!])([a-zA-Z])|([,.?!])([,.?!]\b)

as shown above, four different regex are separated by vertical bar, and by using that, I am trying to give punctuation mark a spacing next to it.

so I tried:

replace with : $1$2 $3|$4$5 $6|$7$8 $9|$10 $11

but it messed up my sample text obviously lols.. only the $2 worked as intended.

I desperately googled up to find solution but so far I couldn't find it.

can you give me a hand? I couldn't be happier!!

**Comment by doug24** [comment] 2020-08-20 14:52
I really can't see what you are trying to do, especially with that last section of the long regex.  But I doubt you are going to have much success that way.  And it doesn't look like you need to construct it that way - I would try to make a simpler expression with just three capture groups, like this:
`([a-zA-Z\d])([,.?!]+)([a-zA-Z\d])`
and replace with this:
`$1$2 $3`

In addition to the regex reference I linked above, here is the Microsoft Regex documentation:
https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expressions

**Comment by doug24** [comment] 2020-09-12 21:19
Fixed in v2.9.270

**Closed** 2020-09-21 14:06 UTC
Labels: bug
