### ISSUE TITLE
Can't search certain docx files

### ISSUE THREAD

**Issue by obolman** [dnGrep/dnGrep#670] opened 2022-05-26 17:05 UTC
For some reason, dnGrep can't find a text string in a certain .docx file. When I saved the same file as .doc it finds the string there!

**Comment by doug24** [comment] 2022-05-26 19:17
Is the text in a normal part of the document, or some other feature?  Do you have an example file to show the problem?  It's hard to debug without having a way to reproduce the issue.

**Comment by obolman** [comment] 2022-05-26 19:33
Hello Doug,

It appears dngrep can’t find anything at all in this document or just completely ignores it. I attached an excerpt from the document.

Please delete the document once you’re done troubleshooting.

Thanks,
Oleg

**Comment by doug24** [comment] 2022-05-26 19:38
I don't see any file attachment.  I don't think you can reply by email and need to upload a zip file on the github issue thread.

**Comment by obolman** [comment] 2022-05-26 19:40
Ok, will do.

**Comment by obolman** [comment] 2022-05-26 19:42
[Sample.docx](https://github.com/dnGrep/dnGrep/files/8781646/Sample.docx)

**Comment by doug24** [comment] 2022-05-26 19:57
There is an exception thrown extracting the text from the document.  I'll have to investigate more.

**Comment by obolman** [comment] 2022-05-26 19:58
Thanks, look forward to a successful resolution!

**Comment by obolman** [comment] 2022-06-01 19:20
Hi Doug,

Any updates? It's been almost a week.

Thanks,
Oleg

**Comment by doug24** [comment] 2022-06-01 22:15
The issue is fixed and will be included in the next release.  It should be out soon.

**Comment by obolman** [comment] 2022-06-01 22:56
Great, thank you! I assume you (or somebody else) will let me know when it's out.

**Comment by obolman** [comment] 2022-06-03 23:42
Works great, thanks for the quick turnaround!

**Closed** 2022-06-26 23:18 UTC

**Comment by doug24** [comment] 2022-11-23 23:21
@abtxu
Can you check the dnGrep log file to see if there is an error logged? 
C:\Users\_username_\AppData\Roaming\dnGREP\logs

I can't fix anything without more information.  If you want to help, you can try to isolate the problem in the docx file.  Make two copies of the document, and delete the first half of the document from one, and the second half from the other.  Does the search work in one and fail in the other?  If so, keep repeating this until you find a small sample.

**Comment by fade2gray** [comment] 2022-11-23 23:56
Just for the record:

> To attach a file to an issue or pull request conversation, drag and drop it into the comment box. Alternatively, you can click the bar at the bottom of the comment box to browse, select, and add a file from your computer.

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

If it's a large text file, it may be best to zip it first.
