### ISSUE TITLE
Notified of new version, but nothing happens when clicking "Yes"

### ISSUE THREAD

**Issue by fade2gray** [dnGrep/dnGrep#935] opened 2023-08-28 00:07 UTC
Installed version: 4.0.26.0

![DownloadLatest](https://github.com/dnGrep/dnGrep/assets/1332009/8ab77a6d-a0a0-4c48-abf1-dfae37087d1b)

**Comment by doug24** [comment] 2023-08-28 00:11
Duplicate of #881.  Install the latest version here:  https://github.com/dnGrep/dnGrep/releases/tag/v4.0.69.0

**Closed by doug24** 2023-08-28 00:11 UTC
Labels: duplicate
